name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generates the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          # Your GitHub username (replace 'AdminAdi' with your username)
          github_user_name: AdminAdi
          # Output format (svg/png)
          output: dist/snake.svg

      # Pushes the animation to the repository
      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mv dist/snake.svg assets/snake.svg
          git add assets/snake.svg
          git commit -m "Updated Snake Animation"
          git push
